<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Filters\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DocsApi.Core\DocsApi.Core.csproj" />
      <ProjectReference Include="..\DocsApi.Infrastructure\DocsApi.Infrastructure.csproj" />
    </ItemGroup>

</Project>
